language: python

python:
  - "3.13"

before_install:
  - pip install --upgrade awsebcli

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test

after_script:
  - coveralls

deploy:
  provider: script
  script: |
    eb init django-tutorial \
      --platform "Python 3.13" \
      --region $AWS_DEFAULT_REGION
    eb use django-tutorial-env
    eb deploy
  on:
    branch: main
